export enum DbAppEntitiesNames {
  addressBalances = 'address_balances',
  addressTransactionCounts = 'address_transaction_counts',
  addresses = 'addresses',
  currencies = 'currencies',
  fullnodeFeeBaseTransactions = 'fullnode_fee_base_transactions',
  inputBaseTransactions = 'input_base_transactions',
  networkFeeBaseTransactions = 'network_fee_base_transactions',
  receiverBaseTransactions = 'receiver_base_transactions',
  transactionsAddresses = 'transaction_addresses',
  transactions = 'transactions',
  tokenMintingFeeBaseTransactions = 'token_minting_fee_base_transactions',
  tokenGenerationFeeBaseTransactions = 'token_generation_fee_base_transactions',
  originatorCurrencyData = 'originator_currency_data',
  currencyTypeData = 'currency_type_data',
  tokenGenerationServiceData = 'token_generation_service_data',
  tokenMintingServiceData = 'token_minting_service_data',
}
