name: build

on:
  workflow_dispatch:
  push:
    branches:
      - dev
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        APP: [explorer-api, live-app]
        NODE_VERSION: [16.x, 18.x]

    steps:
      - name: Clone
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.NODE_VERSION }}

      - name: Build ${{ matrix.APP }}
        run: | 
          npm ci
          npm run build-${{ matrix.APP }}
